"""Generate the evidence summary from artifact JSON.

Every gate verdict in this repository must be rendered from a recorded artifact rather than
written by hand. Hand-written verdicts drifted from the artifacts they claimed to summarize:
`WALKTHROUGH.md` reported "ECE Passed" for a workload whose artifact recorded
`gate_brier_passed: false`, and the M4 tables reported improved reliability for two runs that
both recorded `gate_ece_passed: false`.

This module walks the artifact tree, collects every boolean whose key names a gate, and writes
`EVIDENCE.md`. The `check` subcommand fails when the committed file no longer matches the
artifacts, so documentation drift is a test failure rather than a reading-comprehension exercise.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

GENERATED_HEADER = "<!-- Generated by `jah-report generate`. Do not edit by hand. -->"

METRIC_KEYS = (
    "accuracy",
    "balanced_accuracy",
    "macro_f1",
    "normalized_mae",
    "quadratic_weighted_kappa",
    "brier_score",
    "prevalence_brier_score",
    "prevalence_brier",
    "ece",
    "nll",
    "coverage",
    "accepted_count",
    "accepted_error_rate",
    "accepted_error_95_upper_bound",
    "argmax_agreement",
    "maximum_probability_deviation",
    "policy_flips",
)


def _is_gate_key(key: str) -> bool:
    return "gate" in key.lower() and "_passed" in key.lower()


def walk(node: Any, path: tuple[str, ...] = ()) -> list[tuple[tuple[str, ...], Any]]:
    """Yield every leaf in a JSON document with its dotted path."""
    leaves: list[tuple[tuple[str, ...], Any]] = []
    if isinstance(node, dict):
        for key in sorted(node):
            leaves.extend(walk(node[key], (*path, str(key))))
    elif isinstance(node, list):
        for index, item in enumerate(node):
            leaves.extend(walk(item, (*path, f"[{index}]")))
    else:
        leaves.append((path, node))
    return leaves


def collect_gates(document: Any) -> list[tuple[str, bool]]:
    return [
        (".".join(path), value)
        for path, value in walk(document)
        if isinstance(value, bool) and _is_gate_key(path[-1])
    ]


def collect_metrics(document: Any) -> list[tuple[str, float]]:
    return [
        (".".join(path), value)
        for path, value in walk(document)
        if isinstance(value, (int, float))
        and not isinstance(value, bool)
        and path[-1] in METRIC_KEYS
    ]


def _load_artifacts(artifacts_dir: Path) -> list[tuple[Path, Any]]:
    loaded = []
    for path in sorted(artifacts_dir.rglob("*.json")):
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"{path} is not valid JSON evidence") from exc
        loaded.append((path, document))
    if not loaded:
        raise ValueError(f"no artifacts found under {artifacts_dir}")
    return loaded


def _format_number(value: float) -> str:
    if isinstance(value, int):
        return str(value)
    if value == 0 or 1e-4 <= abs(value) < 1e6:
        return f"{value:.6f}".rstrip("0").rstrip(".")
    return f"{value:.3e}"


def render(root: Path, artifacts_dir: Path) -> str:
    artifacts = _load_artifacts(artifacts_dir)
    lines = [
        GENERATED_HEADER,
        "",
        "# Evidence summary",
        "",
        "Every row below is read directly out of a recorded artifact. A `false` verdict means the",
        "gate was measured and not met. An absent gate means it was never measured, which the",
        "specification treats as unvalidated rather than passed.",
        "",
        "Regenerate with `jah-report generate`; `jah-report check` fails when this file drifts",
        "from the artifacts.",
        "",
    ]

    total_gates = 0
    passed_gates = 0
    gate_sections = []
    for path, document in artifacts:
        gates = collect_gates(document)
        metrics = collect_metrics(document)
        if not gates and not metrics:
            continue
        relative = path.relative_to(root).as_posix()
        section = [f"## `{relative}`", ""]
        for key in ("source_commit_sha", "evidence_sha256", "dataset_sha256", "created_at"):
            if isinstance(document, dict) and document.get(key) is not None:
                section.append(f"- `{key}`: `{document[key]}`")
        if section[-1] != "":
            section.append("")

        if gates:
            total_gates += len(gates)
            passed_gates += sum(1 for _, value in gates if value)
            section.extend(["| Gate | Verdict |", "| --- | --- |"])
            for name, value in gates:
                section.append(f"| `{name}` | **{'pass' if value else 'FAIL'}** |")
            section.append("")
        if metrics:
            section.extend(["| Measure | Value |", "| --- | --- |"])
            for name, value in metrics:
                section.append(f"| `{name}` | {_format_number(value)} |")
            section.append("")
        gate_sections.append("\n".join(section))

    lines.extend(
        [
            f"**{passed_gates} of {total_gates} recorded gates pass.**",
            "",
            "---",
            "",
        ]
    )
    lines.append("\n".join(gate_sections))
    return "\n".join(lines).rstrip() + "\n"


def generate(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    content = render(root, root / args.artifacts)
    output_path = root / args.output
    with output_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"Wrote {output_path.relative_to(root).as_posix()}")
    return 0


def check(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    expected = render(root, root / args.artifacts)
    output_path = root / args.output
    if not output_path.exists():
        raise FileNotFoundError(
            f"{args.output} is missing; run `jah-report generate` after changing artifacts"
        )
    actual = output_path.read_text(encoding="utf-8")
    if actual != expected:
        raise ValueError(
            f"{args.output} is stale relative to the artifacts; run `jah-report generate`"
        )
    print(f"{args.output} matches the artifacts.")
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=Path.cwd())
    parser.add_argument("--artifacts", default="artifacts")
    parser.add_argument("--output", default="EVIDENCE.md")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("generate").set_defaults(function=generate)
    subparsers.add_parser("check").set_defaults(function=check)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    return args.function(args)


if __name__ == "__main__":
    raise SystemExit(main())
